name       : openvdb
version    : 7.1.0
release    : 1
source     :
    - https://github.com/AcademySoftwareFoundation/openvdb/archive/v7.1.0.tar.gz : 0c3588c1ca6e647610738654ec2c6aaf41a203fd797f609fbeab1c9f7c3dc116
license    : MPL-2.0
component  : multimedia.library
homepage   : https://www.openvdb.org/
summary    : Sparse volume data structure and tools
description: |
    OpenVDB is an open source C++ library comprising a novel hierarchical data structure and a large suite of tools for the efficient storage and manipulation of sparse volumetric data discretized on three-dimensional grids. It was developed by DreamWorks Animation for use in volumetric applications typically encountered in feature film production.
avx2       : yes
builddeps  :
    - pkgconfig(IlmBase)
    - pkgconfig(OpenEXR)
    - pkgconfig(blosc)
    - pkgconfig(jemalloc)
    - intel-tbb-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DOPENVDB_CORE_STATIC=0
build      : |
    %ninja_build
install    : |
    %ninja_install
