name       : openvdb
version    : 8.1.0
release    : 5
source     :
    - https://github.com/AcademySoftwareFoundation/openvdb/archive/refs/tags/v8.1.0.tar.gz : 3e09d47331429be7409a3a3c27fdd3c297f96d31d2153febe194e664a99d6183
homepage   : https://www.openvdb.org/
license    : MPL-2.0
component  : multimedia.library
summary    : Sparse volume data structure and tools
description: |
    OpenVDB is an open source C++ library comprising a novel hierarchical data structure and a large suite of tools for the efficient storage and manipulation of sparse volumetric data discretized on three-dimensional grids. It was developed by DreamWorks Animation for use in volumetric applications typically encountered in feature film production.
avx2       : yes
builddeps  :
    - pkgconfig(blosc)
    - pkgconfig(python3)
    - intel-tbb-devel
    - libboost-devel
    - numpy
rundeps    :
    - numpy
setup      : |
    %patch -p1 < $pkgfiles/cmake-pyopenvdb-site-packages.patch
    %cmake_ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DUSE_NUMPY=ON \
        -DDISABLE_DEPENDENCY_VERSION_CHECKS=ON \
        -DOPENVDB_CORE_STATIC=OFF \
        -DOPENVDB_BUILD_PYTHON_MODULE=ON \
        -DOPENVDB_ENABLE_RPATH=OFF \
        -DOPENVDB_BUILD_UNITTESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    if [[ ! -z "${AVX2BUILD}" ]]; then
        %python3_avx2_lib_shift
    fi
