name       : openvdb
version    : 8.0.0
release    : 3
source     :
    - https://github.com/AcademySoftwareFoundation/openvdb/archive/v8.0.0.tar.gz : 04a28dc24a744f8ac8bbc5636a949628edb02b7c84db24ad795429c8c739a9ee
license    : MPL-2.0
component  : multimedia.library
homepage   : https://www.openvdb.org/
summary    : Sparse volume data structure and tools
description: |
    OpenVDB is an open source C++ library comprising a novel hierarchical data structure and a large suite of tools for the efficient storage and manipulation of sparse volumetric data discretized on three-dimensional grids. It was developed by DreamWorks Animation for use in volumetric applications typically encountered in feature film production.
avx2       : yes
builddeps  :
    - pkgconfig(IlmBase)
    - pkgconfig(OpenEXR)
    - pkgconfig(blosc)
    - pkgconfig(jemalloc)
    - intel-tbb-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DOPENVDB_CORE_STATIC=0
build      : |
    %ninja_build
install    : |
    %ninja_install
